---
eureka:
  client:
    serviceUrl:
#      defaultZone: http://eureka-primary:8010/eureka/,http://eureka-secondary:8011/eureka/,http://eureka-tertiary:8012/eureka/
      defaultZone: http://eureka-primary:8010/eureka/
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
# ---
# spring:
#   profiles: primary
#   application:
#     name: eureka-primary
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://eureka-secondary:8011/eureka/,http://eureka-tertiary:8012/eureka/
# server:
#   port: 8010
# ---
# spring:
#   profiles: secondary
#   application:
#     name: eureka-secondary
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://eureka-primary:8010/eureka/,http://eureka-tertiary:8012/eureka/
# server:
#   port: 8011
# ---
# spring:
#   profiles: tertiary
#   application:
#     name: eureka-tertiary
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://eureka-primary:8010/eureka/,http://eureka-secondary:8011/eureka/
# server:
#   port: 8012
---
spring:
  config:
    activate:
      on-profile: subject
words: I,You,He,She,It
---
# spring:
#   profiles: verb
spring:
  config:
    activate:
      on-profile: verb
words: ran,knew,had,saw,bought
---
spring:
  config:
    activate:
      on-profile: article
words: ta,the
---
spring:
  config:
    activate:
      on-profile: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely
---
spring:
  config:
    activate:
      on-profile: noun
words: boat,book,vote,seat,backpack,partition,groundhog
