---
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8010/eureka/,http://eureka-secondary:8011/eureka/,http://eureka-tertiary:8012/eureka/
---
spring:
  profiles: primary
  client:
    serviceUrl:
      defaultZone: http://eureka-secondary:8011/eureka/,http://eureka-tertiary:8012/eureka/
server:
  port: 8010
